### ISSUE TITLE
Roadmap for 1.0.0

### ISSUE THREAD

**Issue by warpech** [Starcounter/CssVariablesManager#38]
As presented in https://docs.google.com/presentation/d/1zV5urgw7YVAUMLBm9M2o-tZiiek3ZnjQZ5YXyf3KWV8/edit?usp=sharing, this app needs to be changed. The goal is to turn this app into a tool for applying a common look and feel for Starcounter apps.

- [ ] 1. Rename this app to ColorSchemer 
- [ ] 2. Make ColorSchemer aware of Underwear.css and Uniform.css CSS Variables
- [ ] 3. Make ColorSchemer aware of theming Paper elements
- [ ] 4. Make ColorSchemer aware of theming Vaadin elements

**Comment by warpech** [comment]
Moved to https://github.com/Starcounter/Blending/issues/51 and https://github.com/Starcounter/Blending/issues/52
